from src.configs.models import Model, RunConfig, Step, StepRevision, StepRevisionPool

grok_config_prod = RunConfig(
    final_follow_model=Model.grok_4,
    final_follow_times=5,
    max_concurrent_tasks=40,
    steps=[
        Step(
            instruction_model=Model.grok_4,
            follow_model=Model.grok_4,
            times=10,
            timeout_secs=300,
            include_base64=False,
            use_diffs=True,
        ),
        Step(
            instruction_model=Model.grok_4,
            follow_model=Model.grok_4,
            times=27,
            timeout_secs=300,
            include_base64=False,
            use_diffs=True,
        ),
        # StepRevision(
        #     top_scores_used=5,
        #     instruction_model=Model.grok_4,
        #     follow_model=Model.grok_4,
        #     times_per_top_score=1,
        #     timeout_secs=300,
        #     include_base64=False,
        #     use_diffs=True,
        # ),
        StepRevisionPool(
            top_scores_used=5,
            instruction_model=Model.grok_4,
            follow_model=Model.grok_4,
            times=8,
            timeout_secs=300,
            include_base64=False,
            use_diffs=True,
        ),
    ],
)

grok_config_old = RunConfig(
    final_follow_model=Model.grok_4,
    final_follow_times=5,
    max_concurrent_tasks=10,
    steps=[
        Step(
            instruction_model=Model.grok_4,
            follow_model=Model.grok_4,
            times=20,
            timeout_secs=300,
            include_base64=False,
            use_diffs=True,
        ),
        Step(
            instruction_model=Model.grok_4,
            follow_model=Model.grok_4,
            times=20,
            timeout_secs=300,
            include_base64=False,
            use_diffs=True,
        ),
        # Step(
        #     instruction_model=Model.grok_4,
        #     follow_model=Model.grok_4,
        #     times=20,
        #     timeout_secs=300,
        #     include_base64=False,
        #     use_diffs=True,
        # ),
        StepRevision(
            top_scores_used=5,
            instruction_model=Model.grok_4,
            follow_model=Model.grok_4,
            times_per_top_score=2,
            timeout_secs=300,
            include_base64=False,
            use_diffs=True,
        ),
        StepRevisionPool(
            top_scores_used=5,
            instruction_model=Model.grok_4,
            follow_model=Model.grok_4,
            times=10,
            timeout_secs=300,
            include_base64=False,
            use_diffs=True,
        ),
        # StepRevision(
        #     top_scores_used=5,
        #     instruction_model=Model.grok_4,
        #     follow_model=Model.grok_4,
        #     times_per_top_score=2,
        #     timeout_secs=300,
        #     include_base64=False,
        #     use_diffs=True,
        # ),
        # StepRevisionPool(
        #     top_scores_used=5,
        #     instruction_model=Model.grok_4,
        #     follow_model=Model.grok_4,
        #     times=5,
        #     timeout_secs=300,
        #     include_base64=False,
        #     use_diffs=True,
        # ),
    ],
)
